### ISSUE TITLE
Any way to get the full url of the downloaded file?

### ISSUE THREAD

**Issue by playgithub** [suisei-cn/actions-download-file#11]
So that it can be downloaded from the web browser.

**Comment by outloudvi** [comment]
For now the action should log the URL, if it helps:

<https://github.com/suisei-cn/actions-download-file/blob/872a4077bb19865efb4eeab4787adcb3571a2d23/index.js#L37>

It currently does not have an output for the url (to be consumed by other actions), since the URL is usually given (and in most cases, explicitly) by the user.

**Comment by playgithub** [comment]
I mean for the URL of the downloaded file.

**Comment by outloudvi** [comment]
It does show the URL of the downloaded file.

![image](https://user-images.githubusercontent.com/19144373/193436048-c58a9f85-0548-4661-b0c0-9864cf15d86a.png)

I guess you may mean the final URL after (possibly) redirects?

**Comment by playgithub** [comment]
> I guess you may mean the final URL after (possibly) redirects?

Yes, anyway the URL before redirects is enough.
Thanks
